<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hubungi Kami_totalEmployer</name>
   <tag></tag>
   <elementGuidId>901a3125-593b-4a66-bf7c-e83f20f6d71e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='totalEmployer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;totalEmployer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc5e8c4-3b22-453c-9ca4-b3546931f230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c8408100-71c4-43ab-a166-547e9ffe4014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mb-3 p-3 rounded-lg</value>
      <webElementGuid>ce26bd56-e1de-4c4d-b8eb-000bddcdf38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Karyawan</value>
      <webElementGuid>f76fe93c-b9b8-4d74-af8b-a8aa8150c9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalEmployer</value>
      <webElementGuid>a233664e-1dac-425e-9e5c-a37ad26281d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubscribe&quot;)/input[@class=&quot;w-full mb-3 p-3 rounded-lg&quot;]</value>
      <webElementGuid>d66d0d11-8e6c-48dc-bd5a-f5b4ae85fe0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='totalEmployer']</value>
      <webElementGuid>296fedfd-456d-45ac-bce5-76d6228505b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubscribe']/input[5]</value>
      <webElementGuid>328de425-ab67-461e-8cd4-7b0a3137b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>81503ed5-3497-4502-bc38-f5f20d9780ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Jumlah Karyawan' and @name = 'totalEmployer']</value>
      <webElementGuid>576856b1-3805-438b-925b-0313020d2d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
