<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hubungi Kami_company</name>
   <tag></tag>
   <elementGuidId>3310bcc0-5846-43a4-ba95-99852d8a3be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;company&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f32d9f15-4e5f-40fc-89bd-9e82397eb6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb6a0306-00a0-467f-bc4b-b562e83eba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mb-3 p-3 rounded-lg</value>
      <webElementGuid>595b9fad-be72-4614-8784-e86382abdacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Perusahaan</value>
      <webElementGuid>9596c263-3e97-4f12-b4ca-ce6d19db488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>b61bb59c-983a-4be0-a293-78bc5ab9b128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubscribe&quot;)/input[@class=&quot;w-full mb-3 p-3 rounded-lg&quot;]</value>
      <webElementGuid>ba4b3803-4c08-4e35-9088-047225ad5adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='company']</value>
      <webElementGuid>5d324173-6782-4bc6-9640-8f8c388dd9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubscribe']/input[4]</value>
      <webElementGuid>bb3e668a-6cce-4a8b-bf3e-f83ed1f20750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>eb1cb630-de24-474e-a324-a85052fb71da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama Perusahaan' and @name = 'company']</value>
      <webElementGuid>393bc6d0-8ee4-4971-a0c2-ef120e03ac71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
